### ISSUE TITLE
Replay Memory (problem?)

### ISSUE THREAD

**Issue by camigord** [cgel/DRL#1]
Hey @cgel,

I have been studying your code since you posted in [dennybritz](https://github.com/dennybritz/reinforcement-learning) repo and it has been really helpful!!

I have one comment regarding the Replay Memory Class. If I am not wrong, you use the following line to avoid sampling terminal states from the RM:
```
if self.terminals[(index - self.buff_size -1):index].any():
     continue
```
 But I would say that the conditional should be more like:

`if self.terminals[(index - self.buff_size +1):index+1].any():`

So that you verify that none of the last _buff_size_ frames are terminal. Ideally, however, there should be another logic block taking care of verifying that _index_ is not smaller than  _buff_size_, and if it is, check also the last entries of the RM (similar to what it's done in the function _get_state_).

I hope I was clear XD. Thanks again for sharing the code, it helped me a lot.

**Comment by cgel** [comment]
Hi, sorry I took so long to replay.

We want to sample states that are terminal so that DQN can learn that they have a low value. If we don't sample them, when the terminal state is the next state the low value will not propagate and the agent won't learn.

But you are right that there is a mistake. The line should be:
```
if self.terminals[(index - self.buff_size):index].any():
     continue
```

Regarding the second point. If the memory has not been filled we only sample states beginning at self.buff_size -1 and if the memory has been filled we sample from 0 and let  ```get_state``` take care of it.
